INSERT INTO stadyumlar Values ( 1, 'Arena Amazonia', 'Manaus', 40549)
INSERT INTO stadyumlar Values ( 2, 'Arena da Baixada', 'Cúritiba', 39631)
INSERT INTO stadyumlar Values ( 3, 'Arena de Sao Paulo', 'São Paulo', 62601)
INSERT INTO stadyumlar Values ( 4, 'Arena Fonte Nova', 'Salvador da Bahia', 51900)
INSERT INTO stadyumlar Values ( 5, 'Arena Pantanal', 'Mixto EC, Cuiabá EC', 41112)
INSERT INTO stadyumlar Values ( 6, 'Arena Pernambuco', 'São Lourenço da Mata', 42610)
INSERT INTO stadyumlar Values ( 7, 'Estadio Beira-Rio', 'Pôrto Alegre', 43394)
INSERT INTO stadyumlar Values ( 8, 'Estadio Castelao', 'Fortaleza', 60342)
INSERT INTO stadyumlar Values ( 9, 'Estadio das Dunas', 'Natal', 39971)
INSERT INTO stadyumlar Values ( 10, 'Estadio do Maracana', 'Rio de Janeiro', 74738)
INSERT INTO stadyumlar Values ( 11, 'Estadio Mineirao', 'Belo Horizonte', 58170)
INSERT INTO stadyumlar Values ( 12, 'Estadio Nacional de Brasilia', 'Brasilia', 69349)